#Use official Alpine docker image
FROM alpine
LABEL pace=true
WORKDIR /
ADD run.sh /run.sh
RUN apk update && apk add git make openjdk11 procps && \
    git clone https://github.com/twalgor/tw.git && \
    find -name "*.java" > sources.txt && \
    javac $(find ./tw/* | grep .java) && \
    chmod +x run.sh
